### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by zbeekman** [leetmaa/bitsy#2]
It looks like you’re using a tool to document this… which tool are you using? Doxygen? Can you add the invocation of the documentation generator to the README.md or tell me how to generate it?

Thanks

**Comment by leetmaa** [comment]
I was more interested in a standardized way of documenting the code, rather than having a full code manual built, so I haven't tried to generate a manual. But yes, I've used Doxgen comments. You can see how it is used for fortran here: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#fortranblocks If you want to generate documentation you'll have to use Doxygen for that.
